### ISSUE TITLE
[DK] Copenhagen Sector Colours

### ISSUE THREAD

**Issue by AlexP2101** [lennycolton/vatglasses-data#111]
The EKDK_D and EKDK_V sectors are next to each other and have the same colour on the VATGlasses page. They are currently being controlled by different controllers.
![image](https://github.com/lennycolton/vatglasses-data/assets/133516782/28c03db5-6029-4c9b-b9bd-e7c9ef90075e)
![image](https://github.com/lennycolton/vatglasses-data/assets/133516782/30627020-fd3a-4f52-b763-5a9977072157)
![image](https://github.com/lennycolton/vatglasses-data/assets/133516782/2db2b208-26ea-4eb8-8880-ce7dd89596ce)

**Comment by lennycolton** [comment]
Copenhagen has recently been resectorised. Is this still an issue? @AlexP2101

**Comment by wuestr** [comment]
This seems to still be an issue @lennycolton. There are now several CTR-sectors with the same colours:
A and C have the same colour
D, E and I have the same colour
L, N, S and V have the same colour

The only sectors with colours different from the ones above are DK (bandbox) and B_CTR.
Not sure if this was intentional or by "mistake" due to copying of other stations.

**Comment by lennycolton** [comment]
Thanks @wuestr!

Denmark ops are going to handle this. Some sectors should be the same colour but the current combinations are wrong. They don't have GitHub so I'll push the relevant update once done.
