### ISSUE TITLE
Addition of Helsinki FIR

### ISSUE THREAD

**Issue by ottotuhkunen** [lennycolton/vatglasses-data#68]
Hi! I am staff for Vatsim Scandinavia

ACCSCA24 | Training Assistant Finland | Otto Tuhkunen | 

[training-finland@vatsim-scandinavia.org](mailto:training-finland@vatsim-scandinavia.org)

Discord **_Redacted_**

We would like to add Finland to vatglasses.

@lennycolton

**Comment by ottotuhkunen** [comment]
@lennycolton

**Comment by MatisseBE** [comment]
Hi Otto,
At this time, there's multiple people trying to reach Lenny without success. I had personally talked to him before on Discord but have not heard back from him for almost a month now. It's slightly worrying. 

I had uploaded your data to the beta website using the existing Belux json, but the beta site doesn't update from the repo anymore for some reason - so that was of no help.

**Comment by lennycolton** [comment]
Resolved via DM
